In [ ]:
# prompt: connect to drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [ ]:
# prompt: install odfpy

!pip install odfpy

Requirement already satisfied: odfpy in /usr/local/lib/python3.11/dist-packages (1.4.1)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.11/dist-packages (from odfpy) (0.7.1)

In [ ]:
df_annonimized = pd.read_csv('/content/drive/My Drive/CS114_project2/data-tbtl/annonimized.csv')
df_tbtl = pd.read_excel('/content/drive/My Drive/CS114_project2/data-tbtl/tbtl-public.ods')
df_qt = pd.read_csv('/content/drive/My Drive/CS114_project2/public_it001/qt-public.csv')
df_th = pd.read_csv('/content/drive/My Drive/CS114_project2/public_it001/th-public.csv')
df_ck = pd.read_csv('/content/drive/My Drive/CS114_project2/public_it001/ck-public.csv')

In [ ]:
df_th.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hash    761 non-null    object
 1   TH      755 non-null    object
dtypes: object(2)
memory usage: 12.0+ KB

In [ ]:
df_tbtl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799 entries, 0 to 798
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   username  799 non-null    object
 1   TBTL      799 non-null    float64
dtypes: float64(1), object(1)
memory usage: 12.6+ KB

In [ ]:
df_ck.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hash    761 non-null    object
 1   CK      755 non-null    float64
dtypes: float64(1), object(1)
memory usage: 12.0+ KB

In [ ]:
df_qt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hash    761 non-null    object
 1   diemqt  755 non-null    object
dtypes: object(2)
memory usage: 12.0+ KB

In [ ]:
def clean_convert(df):

    # Thay thế ký tự không hợp lệ
    df_clean = df.replace(r'\xa0', '', regex=True)
    # Chuyển đổi kiểu dữ liệu từ object sang float
    df_clean = df_clean.apply(pd.to_numeric, errors='coerce')
    # Xóa các hàng chứa giá trị null
    df_clean = df_clean.dropna()
    return df_clean

# Ví dụ sử dụng:
# df = pd.read_csv('your_data.csv')
# df_cleaned = clean_convert(df)
# print(df_cleaned)

In [ ]:
df_th['TH'] = clean_convert(df_th['TH'])
df_th = df_th.rename(columns={'hash':'username'})
df_qt['diemqt'] = clean_convert(df_qt['diemqt'])
df_qt = df_qt.rename(columns={'hash':'username'})
df_ck['CK'] = clean_convert(df_ck['CK'])
df_ck = df_ck.rename(columns={'hash':'username'})

In [ ]:
df_th.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   username  761 non-null    object
 1   TH        753 non-null    float64
dtypes: float64(1), object(1)
memory usage: 12.0+ KB

In [ ]:
df_annonimized.head()

,"concat('it001',`assignment_id`)","concat('it001',`problem_id`)","concat('it001', username)",is_final,status,pre_score,coefficient,"concat('it001',`language_id`)",created_at,updated_at,judgement
0,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,0,SCORE,0,100,it0012,10-09 08:02:04,10-09 08:06:58,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0..."
1,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,0,SCORE,0,100,it0012,10-09 08:04:41,10-09 08:04:51,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0..."
2,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 08:06:49,10-09 08:06:58,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0..."
3,90ce27571176d87961b565d5ef4b3de33ede04ac,bf96fbdc5f499538c3e2bfbec5779c8a14b0a9ff,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 08:47:52,10-09 08:48:01,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0..."
4,90ce27571176d87961b565d5ef4b3de33ede04ac,7a6e5ca470ff47c3b5048f240c4738de71010c78,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 09:19:35,10-09 09:19:45,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0..."

In [ ]:
df_annonimized['status'].value_counts()

status
SCORE                235501
Compilation Error     59630
Syntax Error             57
pending                  10
Name: count, dtype: int64

In [ ]:
df_annonimized[['month_day', 'time']] = df_annonimized['created_at'].str.split(' ', expand=True)

# Data Preparation

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
df_annonimized

,"concat('it001',`assignment_id`)","concat('it001',`problem_id`)","concat('it001', username)",is_final,status,pre_score,coefficient,"concat('it001',`language_id`)",created_at,updated_at,judgement,month_day,time
0,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,0,SCORE,0,100,it0012,10-09 08:02:04,10-09 08:06:58,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0...",10-09,08:02:04
1,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,0,SCORE,0,100,it0012,10-09 08:04:41,10-09 08:04:51,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0...",10-09,08:04:41
2,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 08:06:49,10-09 08:06:58,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0...",10-09,08:06:49
3,90ce27571176d87961b565d5ef4b3de33ede04ac,bf96fbdc5f499538c3e2bfbec5779c8a14b0a9ff,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 08:47:52,10-09 08:48:01,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0...",10-09,08:47:52
4,90ce27571176d87961b565d5ef4b3de33ede04ac,7a6e5ca470ff47c3b5048f240c4738de71010c78,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 09:19:35,10-09 09:19:45,"{""times"":[0,0,0,0,0,0,0,0,0,0],""mems"":[0,0,0,0...",10-09,09:19:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295193,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,388516cbf597351226be1bdbe5ef30b9dcef570f,232cce96362898f08e9150ba244adaf2d6583ab2,1,SCORE,10000,100,it0012,01-15 16:03:43,01-15 16:03:53,"{""times"":[0,0,0,0,0,0,0,0,0,0,0,0,0,0],""mems"":...",01-15,16:03:43
295194,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,d2b96124ccb8e27b4b8dacdb935e729cb1ba546b,232cce96362898f08e9150ba244adaf2d6583ab2,0,Compilation Error,0,100,it0012,01-15 16:04:07,01-15 16:05:08,"{""times"":[],""mems"":[],""verdicts"":{""\n\nIn func...",01-15,16:04:07
295195,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,d2b96124ccb8e27b4b8dacdb935e729cb1ba546b,232cce96362898f08e9150ba244adaf2d6583ab2,1,SCORE,10000,100,it0012,01-15 16:04:58,01-15 16:05:08,"{""times"":[0,0,0,0,0,0,0,0,0,0,0,0,0,0],""mems"":...",01-15,16:04:58
295196,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,8c0f8dd4ff55e1609f733e043ac5e88b1dde6e7c,232cce96362898f08e9150ba244adaf2d6583ab2,1,SCORE,10000,100,it0012,01-15 16:05:13,01-15 16:05:22,"{""times"":[0,0,0,0,0,0,0,0,0,0,0,0,0],""mems"":[0...",01-15,16:05:13
295197,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,e1baec9d1d9af44372188067b55edfec747f1342,232cce96362898f08e9150ba244adaf2d6583ab2,1,SCORE,10000,100,it0012,01-15 16:05:40,01-15 16:05:50,"{""times"":[0,0,0,0,0,0,0,0,0,0,0,0,0,0],""mems"":...",01-15,16:05:40

In [ ]:
#Tách các giá trị trong cột status thành từng cột riêng
df_annonimized['SCORE'] = df_annonimized['status'].apply(lambda x: 1 if x == 'SCORE' else 0)
df_annonimized['Compilation Error'] = df_annonimized['status'].apply(lambda x: 1 if x == 'Compilation Error' else 0)
df_annonimized['Syntax Error'] = df_annonimized['status'].apply(lambda x: 1 if x == 'Syntax Error' else 0)
df_annonimized['pending'] = df_annonimized['status'].apply(lambda x: 1 if x == 'pending' else 0)

df_annonimized['final'] = df_annonimized['is_final'].apply(lambda x: 1 if x == 1 else 0)
df_annonimized['not_final'] = df_annonimized['is_final'].apply(lambda x: 1 if x == 0 else 0)
df_annonimized['success'] = df_annonimized['pre_score'].apply(lambda x: 1 if x == 10000 else 0)
df_annonimized['non_success'] = df_annonimized['pre_score'].apply(lambda x: 1 if x != 10000 else 0)

df_annonimized

,"concat('it001',`assignment_id`)","concat('it001',`problem_id`)","concat('it001', username)",is_final,status,pre_score,coefficient,"concat('it001',`language_id`)",created_at,updated_at,...,month_day,time,SCORE,Compilation Error,Syntax Error,pending,final,not_final,success,non_success
0,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,0,SCORE,0,100,it0012,10-09 08:02:04,10-09 08:06:58,...,10-09,08:02:04,1,0,0,0,0,1,0,1
1,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,0,SCORE,0,100,it0012,10-09 08:04:41,10-09 08:04:51,...,10-09,08:04:41,1,0,0,0,0,1,0,1
2,90ce27571176d87961b565d5ef4b3de33ede04ac,789454427dd4097a14749e3dde63346b7a8d3811,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 08:06:49,10-09 08:06:58,...,10-09,08:06:49,1,0,0,0,1,0,1,0
3,90ce27571176d87961b565d5ef4b3de33ede04ac,bf96fbdc5f499538c3e2bfbec5779c8a14b0a9ff,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 08:47:52,10-09 08:48:01,...,10-09,08:47:52,1,0,0,0,1,0,1,0
4,90ce27571176d87961b565d5ef4b3de33ede04ac,7a6e5ca470ff47c3b5048f240c4738de71010c78,ed9eaeb6a707f50154024b24d7efcb874a9795dd,1,SCORE,10000,100,it0012,10-09 09:19:35,10-09 09:19:45,...,10-09,09:19:35,1,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295193,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,388516cbf597351226be1bdbe5ef30b9dcef570f,232cce96362898f08e9150ba244adaf2d6583ab2,1,SCORE,10000,100,it0012,01-15 16:03:43,01-15 16:03:53,...,01-15,16:03:43,1,0,0,0,1,0,1,0
295194,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,d2b96124ccb8e27b4b8dacdb935e729cb1ba546b,232cce96362898f08e9150ba244adaf2d6583ab2,0,Compilation Error,0,100,it0012,01-15 16:04:07,01-15 16:05:08,...,01-15,16:04:07,0,1,0,0,0,1,0,1
295195,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,d2b96124ccb8e27b4b8dacdb935e729cb1ba546b,232cce96362898f08e9150ba244adaf2d6583ab2,1,SCORE,10000,100,it0012,01-15 16:04:58,01-15 16:05:08,...,01-15,16:04:58,1,0,0,0,1,0,1,0
295196,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,8c0f8dd4ff55e1609f733e043ac5e88b1dde6e7c,232cce96362898f08e9150ba244adaf2d6583ab2,1,SCORE,10000,100,it0012,01-15 16:05:13,01-15 16:05:22,...,01-15,16:05:13,1,0,0,0,1,0,1,0
295197,613aea04c978f5e72fffc8bcff1f7b695a63f7b1,e1baec9d1d9af44372188067b55edfec747f1342,232cce96362898f08e9150ba244adaf2d6583ab2,1,SCORE,10000,100,it0012,01-15 16:05:40,01-15 16:05:50,...,01-15,16:05:40,1,0,0,0,1,0,1,0

In [ ]:
df_annonimized.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295198 entries, 0 to 295197
Data columns (total 21 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   concat('it001',`assignment_id`)  295198 non-null  object
 1   concat('it001',`problem_id`)     295198 non-null  object
 2   concat('it001', username)        295198 non-null  object
 3   is_final                         295198 non-null  int64
 4   status                           295198 non-null  object
 5   pre_score                        295198 non-null  int64
 6   coefficient                      295198 non-null  int64
 7   concat('it001',`language_id`)    295198 non-null  object
 8   created_at                       295198 non-null  object
 9   updated_at                       295198 non-null  object
 10  judgement                        295198 non-null  object
 11  month_day                        295198 non-null  object
 12  time                             295198 non-null  object
 13  SCORE                            295198 non-null  int64
 14  Compilation Error                295198 non-null  int64
 15  Syntax Error                     295198 non-null  int64
 16  pending                          295198 non-null  int64
 17  final                            295198 non-null  int64
 18  not_final                        295198 non-null  int64
 19  success                          295198 non-null  int64
 20  non_success                      295198 non-null  int64
dtypes: int64(11), object(10)
memory usage: 47.3+ MB

In [ ]:
# Loại bỏ tiền tố, hậu tố và các ký tự không cần thiết
df_annonimized.columns = [
    col.replace("concat('it001',", "").replace("`", "").replace(")", "").strip()
    for col in df_annonimized.columns
]

# In lại danh sách cột để kiểm tra
print(df_annonimized.columns)

Index(['assignment_id', 'problem_id', 'username', 'is_final', 'status',
       'pre_score', 'coefficient', 'language_id', 'created_at', 'updated_at',
       'judgement', 'month_day', 'time', 'SCORE', 'Compilation Error',
       'Syntax Error', 'pending', 'final', 'not_final', 'success',
       'non_success'],
      dtype='object')

In [ ]:
df_synthesis_origin = df_annonimized.groupby(['username']).agg(
     nums_assignment = ('assignment_id', "nunique"),
     nums_problem = ('problem_id', 'nunique'),
     nums_submissions = ('problem_id', 'count'),
     pre_score_mean = ('pre_score', 'mean'),
     pre_score_sum = ('pre_score', 'sum'),
     nums_problem_success = ('success', 'sum'),
     score_count=('SCORE', 'sum'),
     compilation_error_count=('Compilation Error', 'sum'),
     coefficient_mean=('coefficient', 'mean'),
     pending_count=('pending', 'sum'),
     syntax_error_count=('Syntax Error', 'sum'),
     is_final = ('final', "sum"),
     is_not_final = ('not_final', 'sum'),
     month_day = ('month_day', 'nunique')
)

df_synthesis_origin['problem_success_rate'] = df_synthesis_origin['nums_problem_success']/ df_synthesis_origin['nums_submissions']
df_synthesis_origin['problem_non_success_rate'] = 1 - df_synthesis_origin['problem_success_rate']
df_synthesis_origin['total_score_success'] = 10000 * df_synthesis_origin['nums_problem_success']
df_synthesis_origin['submission_frequency'] = df_synthesis_origin['nums_submissions']/df_synthesis_origin['month_day']
df_synthesis_origin['submission_rate'] = df_synthesis_origin['nums_submissions']/df_synthesis_origin['nums_assignment']

df_synthesis_origin

,nums_assignment,nums_problem,nums_submissions,pre_score_mean,pre_score_sum,nums_problem_success,score_count,compilation_error_count,coefficient_mean,pending_count,syntax_error_count,is_final,is_not_final,month_day,problem_success_rate,problem_non_success_rate,total_score_success,submission_frequency,submission_rate
username,,,,,,,,,,,,,,,,,,,
00b6dd4fc7eb817e03708c532016ef30ce564a61,7,46,147,5504.149660,809110,54,119,28,100.000000,0,0,46,101,14,0.367347,0.632653,540000,10.500000,21.000000
00bef8afee8f3c595d535c9c03c490cac1a4f021,9,78,259,5488.552124,1421535,85,209,50,100.000000,0,0,78,181,20,0.328185,0.671815,850000,12.950000,28.777778
01122b3ef7e59b84189e65985305f575d6bdf83c,7,66,195,5973.753846,1164882,59,175,20,100.000000,0,0,67,128,25,0.302564,0.697436,590000,7.800000,27.857143
0134f9f410c65ad0e8c2254a7e9288670e02a183,4,47,100,5952.760000,595276,52,76,24,100.000000,0,0,47,53,13,0.520000,0.480000,520000,7.692308,25.000000
013de369c439ab0ead8aa7da64423aa395a8be39,8,52,107,6474.448598,692766,59,94,13,97.196262,0,0,66,41,8,0.551402,0.448598,590000,13.375000,13.375000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
feb8a2859a011c59efd22ed419cb69288fe03627,9,34,74,5581.081081,413000,40,71,3,100.000000,0,0,34,40,7,0.540541,0.459459,400000,10.571429,8.222222
fef4a3263ed9a8ab14d457694bb8fd86ccd98312,6,77,260,6204.557692,1613185,80,216,44,100.000000,0,0,78,182,16,0.307692,0.692308,800000,16.250000,43.333333
ff12d6e2ab80696ed8e22fbe5497e96c68d29076,6,100,437,4998.466819,2184330,105,360,77,100.000000,0,0,103,334,48,0.240275,0.759725,1050000,9.104167,72.833333
ff3fa2ec64294f37ae968159f810ebeda7966c51,7,34,94,4343.329787,408273,30,74,20,100.000000,0,0,34,60,7,0.319149,0.680851,300000,13.428571,13.428571
ffe872165621d735a48bb5db0c71dd5195cba359,10,96,399,6353.769424,2535154,138,351,48,100.000000,0,0,96,303,26,0.345865,0.654135,1380000,15.346154,39.900000

In [ ]:
df_synthesis_origin.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1489 entries, 00b6dd4fc7eb817e03708c532016ef30ce564a61 to ffe872165621d735a48bb5db0c71dd5195cba359
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   nums_assignment           1489 non-null   int64
 1   nums_problem              1489 non-null   int64
 2   nums_submissions          1489 non-null   int64
 3   pre_score_mean            1489 non-null   float64
 4   pre_score_sum             1489 non-null   int64
 5   nums_problem_success      1489 non-null   int64
 6   score_count               1489 non-null   int64
 7   compilation_error_count   1489 non-null   int64
 8   coefficient_mean          1489 non-null   float64
 9   pending_count             1489 non-null   int64
 10  syntax_error_count        1489 non-null   int64
 11  is_final                  1489 non-null   int64
 12  is_not_final              1489 non-null   int64
 13  month_day                 1489 non-null   int64
 14  problem_success_rate      1489 non-null   float64
 15  problem_non_success_rate  1489 non-null   float64
 16  total_score_success       1489 non-null   int64
 17  submission_frequency      1489 non-null   float64
 18  submission_rate           1489 non-null   float64
dtypes: float64(6), int64(13)
memory usage: 232.7+ KB

In [ ]:
df_synthesis_origin.columns

Index(['nums_assignment', 'nums_problem', 'nums_submissions', 'pre_score_mean',
       'pre_score_sum', 'nums_problem_success', 'score_count',
       'compilation_error_count', 'coefficient_mean', 'pending_count',
       'syntax_error_count', 'is_final', 'is_not_final', 'month_day',
       'problem_success_rate', 'problem_non_success_rate',
       'total_score_success', 'submission_frequency', 'submission_rate'],
      dtype='object')

# Dự đoán điểm

In [ ]:

!pip install scikit-learn==1.3.1

Found existing installation: scikit-learn 1.3.1
Uninstalling scikit-learn-1.3.1:
  Successfully uninstalled scikit-learn-1.3.1
Collecting scikit-learn==1.3.1
  Using cached scikit_learn-1.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.1) (3.5.0)
Using cached scikit_learn-1.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.13.0 requires scikit-learn<2,>=1.3.2, but you have scikit-learn 1.3.1 which is incompatible.
Successfully installed scikit-learn-1.3.1

In [ ]:

# Cài đặt XGBoost với hỗ trợ GPU
!pip install xgboost==2.0.3

Requirement already satisfied: xgboost==2.0.3 in /usr/local/lib/python3.11/dist-packages (2.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from xgboost==2.0.3) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from xgboost==2.0.3) (1.13.1)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
import joblib
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import numpy as np

def find_best_params(df, features, target, title, test_size=0.3, random_state=43):
    # Ensure features are a list
    features = list(features)
    # Get the common columns between features and df.columns
    common_features = list(set(features).intersection(df.columns))
    # Chia dữ liệu thành tập huấn luyện và tập kiểm tra
    X_train, X_test, y_train, y_test = train_test_split(df[features], df[target], test_size=test_size, random_state=random_state)

    # Chuẩn hóa dữ liệu
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Khởi tạo các mô hình và tham số cụ thể cho GridSearchCV
    model_params = {
        'LinearRegression': {
            'model': LinearRegression(),
            'params': {
                'fit_intercept': [True, False],
            }
        },
        'RandomForestRegressor': {
            'model': RandomForestRegressor(random_state=random_state),
            'params': {
                'n_estimators': [100, 200, 500],
                'max_depth': [None, 10, 20, 30],
                'min_samples_split': [2, 5, 10],
                'min_samples_leaf': [1, 2, 4]
            }
        },
        'XGBRegressor': {
            'model': XGBRegressor(random_state=random_state),
            'params': {
                'n_estimators': [100, 200, 300],
                'learning_rate': [0.01, 0.1, 0.3],
                'max_depth': [3, 6, 10],
                'subsample': [0.8, 0.9, 1.0],
                'colsample_bytree': [0.8, 0.9, 1.0]
            }
        }
    }

    # Sử dụng K-fold cross-validation để đánh giá mô hình
    cv = KFold(n_splits=3, shuffle=True, random_state=random_state)
    best_models = {}
    best_model_name = None
    best_score = float('inf')
    best_rmse = float('inf')

    for model_name, mp in model_params.items():
        print(f'Training {model_name}...')
        grid_search = GridSearchCV(estimator=mp['model'], param_grid=mp['params'], scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)

        grid_search.fit(X_train_scaled, y_train)

        best_model = grid_search.best_estimator_
        best_params = grid_search.best_params_

        y_pred = best_model.predict(X_test_scaled)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))

        print(f'RMSE for {model_name}: {rmse}')

        if rmse < best_rmse:
            best_rmse = rmse
            best_model_name = model_name

        best_models[model_name] = {
            'model': best_model,
            'params': best_params,
            'rmse': rmse
        }

        best_model.fit(X_train_scaled, y_train)
        joblib.dump(best_model, f'best_{model_name}_{title}.joblib')

        print(f'Best {model_name} model: {best_model}')
        print(f'Best parameters: {best_params}')

    joblib.dump(scaler, f'scaler_all_models_{title}.joblib')

    print(f'Overall Best Model: {best_model_name} with RMSE: {best_rmse}')
    return best_models, scaler



# best_models, scaler = find_best_params(df, features, target, title)

In [ ]:
def filter_unique_rows(df1, df2, key='username'):
    """
    Lấy các hàng trong df1 mà không có trong df2 dựa trên cột key.

    Args:
    df1 (pd.DataFrame): DataFrame đầu vào 1.
    df2 (pd.DataFrame): DataFrame đầu vào 2.
    key (str): Cột dùng để so sánh. Mặc định là 'username'.

    Returns:
    pd.DataFrame: DataFrame chứa các hàng chỉ có trong df1.
    """
    # Hợp nhất hai DataFrame và thêm cột indicator
    merged_df = df1.merge(df2[[key]], on=key, how='left', indicator=True)

    # Lọc các hàng chỉ có trong df1
    result_df = merged_df[merged_df['_merge'] == 'left_only']

    # Xóa cột indicator
    result_df = result_df.drop(columns=['_merge'])

    return result_df

In [ ]:
# Hàm để dự đoán và lưu kết quả vào file CSV
def predict_and_save(model_filename, scaler_filename, X_pred, username_col='username', output_filename='predictions.csv'):

    # Load model và scaler từ file
    loaded_model = joblib.load(model_filename)
    loaded_scaler = joblib.load(scaler_filename)

    # Chuẩn hóa dữ liệu dự đoán
    X_pred_scaled = loaded_scaler.transform(X_pred.drop(columns=[username_col]))

    # Thực hiện dự đoán
    y_pred = loaded_model.predict(X_pred_scaled)

    # Tạo DataFrame kết quả
    result_df = X_pred[[username_col]].copy()
    result_df['y_pred'] = y_pred

    # Lưu kết quả vào file CSV
    result_df.to_csv(output_filename, index=False)

## Dự đoán điểm Quá trình

In [ ]:
df_qt = pd.merge(df_synthesis_origin,df_qt, on='username', how='inner')
df_qt

,username,nums_assignment,nums_problem,nums_submissions,pre_score_mean,pre_score_sum,nums_problem_success,score_count,compilation_error_count,coefficient_mean,...,syntax_error_count,is_final,is_not_final,month_day,problem_success_rate,problem_non_success_rate,total_score_success,submission_frequency,submission_rate,diemqt
0,00b6dd4fc7eb817e03708c532016ef30ce564a61,7,46,147,5504.149660,809110,54,119,28,100.000000,...,0,46,101,14,0.367347,0.632653,540000,10.500000,21.000000,7.5
1,00bef8afee8f3c595d535c9c03c490cac1a4f021,9,78,259,5488.552124,1421535,85,209,50,100.000000,...,0,78,181,20,0.328185,0.671815,850000,12.950000,28.777778,7.0
2,01122b3ef7e59b84189e65985305f575d6bdf83c,7,66,195,5973.753846,1164882,59,175,20,100.000000,...,0,67,128,25,0.302564,0.697436,590000,7.800000,27.857143,9.0
3,013de369c439ab0ead8aa7da64423aa395a8be39,8,52,107,6474.448598,692766,59,94,13,97.196262,...,0,66,41,8,0.551402,0.448598,590000,13.375000,13.375000,10.0
4,014c59c6433fd764a0b08de6ffeb757eaf60aa73,9,90,199,5240.025126,1042765,79,154,45,100.000000,...,0,90,109,22,0.396985,0.603015,790000,9.045455,22.111111,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,840d07858c03f80f4695056e2cc7d0c474b83a25,6,43,111,5171.639640,574052,41,81,30,100.000000,...,0,44,67,15,0.369369,0.630631,410000,7.400000,18.500000,9.0
757,844f5db2e7e31ae51eba025480679ed7e4708ac6,17,104,357,4785.224090,1708325,108,254,103,100.000000,...,0,104,253,29,0.302521,0.697479,1080000,12.310345,21.000000,8.0
758,845acd04a77b3d1b623f255d9f9f8eae90892dab,8,52,155,4247.296774,658331,47,117,38,100.000000,...,0,53,102,10,0.303226,0.696774,470000,15.500000,19.375000,6.5
759,8460eaaf887a6289fb156f7562fb739ba8e9629e,12,114,557,4278.605027,2383183,113,416,141,100.000000,...,0,115,442,33,0.202873,0.797127,1130000,16.878788,46.416667,10.0
760,8481a7f00c3d30473b01a8a3cff2564948d24902,4,24,54,4444.444444,240000,23,35,19,100.000000,...,0,24,30,4,0.425926,0.574074,230000,13.500000,13.500000,8.0

In [ ]:
df_qt = df_qt.dropna()
df_qt.isna().value_counts()

username  nums_assignment  nums_problem  nums_submissions  pre_score_mean  pre_score_sum  nums_problem_success  score_count  compilation_error_count  coefficient_mean  pending_count  syntax_error_count  is_final  is_not_final  month_day  problem_success_rate  problem_non_success_rate  total_score_success  submission_frequency  submission_rate  diemqt
False     False            False         False             False           False          False                 False        False                    False             False          False               False     False         False      False                 False                     False                False                 False            False     754
Name: count, dtype: int64

In [ ]:
df_qt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 754 entries, 0 to 760
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   username                  754 non-null    object
 1   nums_assignment           754 non-null    int64
 2   nums_problem              754 non-null    int64
 3   nums_submissions          754 non-null    int64
 4   pre_score_mean            754 non-null    float64
 5   pre_score_sum             754 non-null    int64
 6   nums_problem_success      754 non-null    int64
 7   score_count               754 non-null    int64
 8   compilation_error_count   754 non-null    int64
 9   coefficient_mean          754 non-null    float64
 10  pending_count             754 non-null    int64
 11  syntax_error_count        754 non-null    int64
 12  is_final                  754 non-null    int64
 13  is_not_final              754 non-null    int64
 14  month_day                 754 non-null    int64
 15  problem_success_rate      754 non-null    float64
 16  problem_non_success_rate  754 non-null    float64
 17  total_score_success       754 non-null    int64
 18  submission_frequency      754 non-null    float64
 19  submission_rate           754 non-null    float64
 20  diemqt                    754 non-null    float64
dtypes: float64(7), int64(13), object(1)
memory usage: 129.6+ KB

In [ ]:
df_qt.columns

Index(['username', 'nums_assignment', 'nums_problem', 'nums_submissions',
       'pre_score_mean', 'pre_score_sum', 'nums_problem_success',
       'score_count', 'compilation_error_count', 'coefficient_mean',
       'pending_count', 'syntax_error_count', 'is_final', 'is_not_final',
       'month_day', 'problem_success_rate', 'problem_non_success_rate',
       'total_score_success', 'submission_frequency', 'submission_rate',
       'diemqt'],
      dtype='object')

In [ ]:
import sklearn
print(sklearn.__version__)

1.3.1

In [ ]:
# Sử dụng hàm
find_best_params(df_qt, df_synthesis_origin.columns,'diemqt',"qt", test_size=0.3, random_state=43)

Training LinearRegression...
RMSE for LinearRegression: 1.7638824910439648
Best LinearRegression model: LinearRegression()
Best parameters: {'fit_intercept': True}
Training RandomForestRegressor...
RMSE for RandomForestRegressor: 1.7305505755303823
Best RandomForestRegressor model: RandomForestRegressor(max_depth=10, min_samples_leaf=4, n_estimators=500,
                      random_state=43)
Best parameters: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 500}
Training XGBRegressor...
RMSE for XGBRegressor: 1.6976326986126462
Best XGBRegressor model: XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=1.0, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, random_state=43, ...)
Best parameters: {'colsample_bytree': 1.0, 'learning_rate': 0.01, 'max_depth': 6, 'n_estimators': 100, 'subsample': 0.8}
Overall Best Model: XGBRegressor with RMSE: 1.6976326986126462

({'LinearRegression': {'model': LinearRegression(),
   'params': {'fit_intercept': True},
   'rmse': 1.7638824910439648},
  'RandomForestRegressor': {'model': RandomForestRegressor(max_depth=10, min_samples_leaf=4, n_estimators=500,
                         random_state=43),
   'params': {'max_depth': 10,
    'min_samples_leaf': 4,
    'min_samples_split': 2,
    'n_estimators': 500},
   'rmse': 1.7305505755303823},
  'XGBRegressor': {'model': XGBRegressor(base_score=None, booster=None, callbacks=None,
                colsample_bylevel=None, colsample_bynode=None,
                colsample_bytree=1.0, device=None, early_stopping_rounds=None,
                enable_categorical=False, eval_metric=None, feature_types=None,
                gamma=None, grow_policy=None, importance_type=None,
                interaction_constraints=None, learning_rate=0.01, max_bin=None,
                max_cat_threshold=None, max_cat_to_onehot=None,
                max_delta_step=None, max_depth=6, max_leaves=None,
                min_child_weight=None, missing=nan, monotone_constraints=None,
                multi_strategy=None, n_estimators=100, n_jobs=None,
                num_parallel_tree=None, random_state=43, ...),
   'params': {'colsample_bytree': 1.0,
    'learning_rate': 0.01,
    'max_depth': 6,
    'n_estimators': 100,
    'subsample': 0.8},
   'rmse': 1.6976326986126462}},
 StandardScaler())

In [ ]:
# Ví dụ sử dụng hàm
X_pred_qt = filter_unique_rows(df_synthesis_origin, df_qt)
predict_and_save('best_XGBRegressor_qt.joblib', 'scaler_all_models_qt.joblib', X_pred_qt, username_col='username', output_filename='/content/drive/MyDrive/CS114_2/KQ/qt_copy.csv')

## Dự đoán điểm thực hành

In [ ]:
df_th = pd.merge(df_synthesis_origin,df_th, on='username', how='inner')
df_th = df_th.dropna()
# Sử dụng hàm
find_best_params(df_th, df_synthesis_origin.columns,'TH',"th")
# Ví dụ sử dụng hàm
X_pred_th = filter_unique_rows(df_synthesis_origin, df_th)

Training LinearRegression...
RMSE for LinearRegression: 1.9866580931284026
Best LinearRegression model: LinearRegression()
Best parameters: {'fit_intercept': True}
Training RandomForestRegressor...
RMSE for RandomForestRegressor: 1.911792755426694
Best RandomForestRegressor model: RandomForestRegressor(max_depth=10, min_samples_leaf=4, n_estimators=500,
                      random_state=43)
Best parameters: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 500}
Training XGBRegressor...
RMSE for XGBRegressor: 1.9258099455040516
Best XGBRegressor model: XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=300, n_jobs=None,
             num_parallel_tree=None, random_state=43, ...)
Best parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 300, 'subsample': 0.8}
Overall Best Model: RandomForestRegressor with RMSE: 1.911792755426694

In [ ]:
predict_and_save('best_RandomForestRegressor_th.joblib', 'scaler_all_models_th.joblib', X_pred_th, username_col='username', output_filename='/content/drive/MyDrive/CS114_2/KQ/th_copy.csv')

## Dự đoán điểm cuối kì

In [ ]:
df_ck = pd.merge(df_synthesis_origin,df_ck, on='username', how='inner')
df_ck = df_ck.dropna()
# Sử dụng hàm
find_best_params(df_ck, df_synthesis_origin.columns,'CK',"ck")
# Ví dụ sử dụng hàm
X_pred_ck = filter_unique_rows(df_synthesis_origin, df_ck)

Training LinearRegression...
RMSE for LinearRegression: 2.012663780312362
Best LinearRegression model: LinearRegression()
Best parameters: {'fit_intercept': True}
Training RandomForestRegressor...
RMSE for RandomForestRegressor: 2.0126993540005853
Best RandomForestRegressor model: RandomForestRegressor(max_depth=20, n_estimators=200, random_state=43)
Best parameters: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Training XGBRegressor...
RMSE for XGBRegressor: 1.9939824381573827
Best XGBRegressor model: XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=200, n_jobs=None,
             num_parallel_tree=None, random_state=43, ...)
Best parameters: {'colsample_bytree': 0.9, 'learning_rate': 0.01, 'max_depth': 6, 'n_estimators': 200, 'subsample': 0.8}
Overall Best Model: XGBRegressor with RMSE: 1.9939824381573827

In [ ]:
predict_and_save('best_XGBRegressor_qt.joblib', 'scaler_all_models_ck.joblib', X_pred_ck, username_col='username', output_filename='/content/drive/MyDrive/CS114_2/KQ/ck_copy.csv')

## Dự đoán điểm TBTL

In [ ]:
df_tbtl = pd.merge(df_synthesis_origin,df_tbtl, on='username', how='inner')
df_tbtl = df_tbtl.dropna()
# Sử dụng hàm
find_best_params(df_tbtl, df_synthesis_origin.columns,'TBTL',"tbtl")
# Ví dụ sử dụng hàm
X_pred_tbtl = filter_unique_rows(df_synthesis_origin, df_tbtl)

Training LinearRegression...
RMSE for LinearRegression: 0.8480583270401533
Best LinearRegression model: LinearRegression()
Best parameters: {'fit_intercept': True}
Training RandomForestRegressor...
RMSE for RandomForestRegressor: 0.8468359058548712
Best RandomForestRegressor model: RandomForestRegressor(max_depth=10, min_samples_leaf=4, min_samples_split=10,
                      n_estimators=500, random_state=43)
Best parameters: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 500}
Training XGBRegressor...
RMSE for XGBRegressor: 0.8676242955027733
Best XGBRegressor model: XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, random_state=43, ...)
Best parameters: {'colsample_bytree': 0.9, 'learning_rate': 0.01, 'max_depth': 10, 'n_estimators': 100, 'subsample': 0.8}
Overall Best Model: RandomForestRegressor with RMSE: 0.8468359058548712

In [ ]:
predict_and_save('best_LinearRegression_tbtl.joblib', 'scaler_all_models_tbtl.joblib', X_pred_tbtl, username_col='username', output_filename='/content/drive/MyDrive/CS114_2/KQ/tbtl_copy.csv')

## Thực nghiệm:
1. **Dự đoán và đánh giá:** Sử dụng tập kiểm tra để dự đoán và tính toán sai số R^2 để đánh giá mô hình.
2. **Lựa chọn mô hình tốt nhất:** So sánh R^2 của các mô hình khác nhau và chọn mô hình có R^2 cao nhất.
3. **Lưu mô hình và scaler:** Mô hình tốt nhất và scaler được lưu lại sử dụng joblib để sử dụng sau này.